;(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.RepoTool = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
var phrases=['left outer join','right outer join','full outer join','left join','right join','full join','inner join','group by','order by','union all','select','from','where','having','limit','offset','values','set','join','union','and','or'];function protect(input){var values=[],out='';for(var i=0;i<input.length;){var c=input[i],n=input[i+1],start;if(c==="'"||c==='"'||c==='`'){var quote=c;start=i++;while(i<input.length){if(input[i]===quote){if(input[i+1]===quote){i+=2;continue;}i++;break;}if(input[i]==='\\'&&quote!=="'"&&i+1<input.length)i+=2;else i++;}out+='\u0000'+values.length+'\u0000';values.push(input.slice(start,i));continue;}if(c==='-'&&n==='-'){start=i;i+=2;while(i<input.length&&input[i]!=='\n')i++;out+='\u0000'+values.length+'\u0000';values.push(input.slice(start,i));continue;}if(c==='/'&&n==='*'){start=i;i+=2;while(i<input.length&&!(input[i]==='*'&&input[i+1]==='/'))i++;if(i<input.length)i+=2;out+='\u0000'+values.length+'\u0000';values.push(input.slice(start,i));continue;}out+=c;i++;}return{text:out,values:values};}function tokenize(input){return protect(String(input||'')).values;}function format(input){var held=protect(String(input||'')),out=held.text;phrases.forEach(function(p){var re=new RegExp('\\b'+p.replace(' ','\\s+')+'\\b','gi');out=out.replace(re,p.toUpperCase());});out=out.replace(/\s*,\s*/g,', ').replace(/[ \t]+/g,' ');out=out.replace(/\s+(SELECT|FROM|WHERE|HAVING|GROUP BY|ORDER BY|LIMIT|OFFSET|UNION(?: ALL)?|LEFT(?: OUTER)? JOIN|RIGHT(?: OUTER)? JOIN|FULL(?: OUTER)? JOIN|INNER JOIN|JOIN)\b/g,'\n$1');out=out.replace(/\s+(AND|OR)\b/g,'\n  $1');out=out.replace(/\u0000(\d+)\u0000/g,function(_,index){return held.values[+index];});return out.trim();}
async function process(input){var output=format(input);return{output:output,summary:output.split('\n').length+' formatted lines'};}
  return { process: process, format: format, tokenize: tokenize };
});
